add videos
kiwitcms/kiwitcms.github.io pull request #44
Opened 2019-06-29 10:20 UTC by SashoStoichkov

2019-07-18 09:05 UTC, atodorov requested changes

2019-07-18 09:05 UTC, atodorov commented on content/scripts/video.js
> +var player;
Renamed file, not loaded in index.html page

2019-07-18 09:05 UTC, atodorov commented on content/scripts/video.js
> +    player = new YT.Player(id);
See:
https://developers.google.com/youtube/iframe_api_reference#Loading_a_Video_Player

from what I understand we can have 1 player on the page (b/c it is created when the API functions load and call `onYouTubeIframeAPIReady()`. However we should be able to point to different video ID's.

This means we can probably keep the original iframe from the demo video but change `showVideo()` to play a different file for the various buttons. You have to experiment with it.

2019-07-22 08:48 UTC, atodorov requested changes

2019-07-22 08:48 UTC, atodorov commented on content/scripts/video.js
> +function hideVideo(id) {
`id` parameter not used. Remove it.

2019-07-22 13:45 UTC, atodorov requested changes
squash all commits together

2019-07-22 13:45 UTC, atodorov commented on theme/static/style/style.css
> +    background-image: url('../../images/conf/fosdem.png');
Use `/images/....` absolute URL

2019-07-22 13:45 UTC, atodorov commented on theme/static/style/style.css
> +    background-color: inherit;
not needed, remove

2019-07-22 13:45 UTC, atodorov commented on content/pages/index.html
> +                        <i class="fa fa-play fa-2x"></i>
Remove `fa-2x`, let's use a smaller play button here. Larger ones will make the section look busier when you add more of them.

2019-07-22 13:45 UTC, atodorov commented on theme/static/style/style.css
> +    float: left;
This div is out of alignment with the rest of the images. Use `margin-left: 1.5rem;`

2019-07-22 17:39 UTC, atodorov requested changes

2019-07-22 17:39 UTC, atodorov commented on content/pages/index.html
> +                        <i class="fa fa-play fa-x"></i>
There is no `fa-x` class.

2019-07-23 07:54 UTC, atodorov requested changes
almost there

2019-07-23 07:54 UTC, atodorov commented on content/pages/index.html
> +                        <i class="fa fa-play fa-lg"></i>
Remove `fa-lg`, see previous comment.

2019-07-23 10:51 UTC, SashoStoichkov commented
I thing it's ready

2019-07-23 11:22 UTC, atodorov approved these changes

2019-07-23 11:23 UTC, merged